name: Update News Information

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * Sun'
    - cron: '*/5 * * * Mon-Fri'
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: set up python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          
      - name: prepare release
        uses: actions/checkout@v3
        with: 
          path: release
          ref: main
          
      - name: prepare generater
        uses: actions/checkout@v3
        with: 
          repository: Qst236/getnews
          ssh-key: ${{ secrets.GETNEWS }}
          path: getnews
          ref: main

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('getnews/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      - name: install dependencies
        run: |
          pip install -r getnews/requirements.txt
          python3 getnews/main.py --file release/news.json
          
      - name: set variables
        run: |
          echo "UPDATE_TIME=$(TZ='Asia/Jakarta' date +%Y-%m-%d\ %H:%M)" >> $GITHUB_ENV
      
      - name: send webhook
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          UPDATE_TIME: ${{ env.UPDATE_TIME }}
        run: |
          cd release
          python3 main.py
      
      - name: push release
        run: |
          git -C release config --local user.name github-actions
          git -C release config --local user.email github-actions@github.com
          git -C release add data.json
          git -C release commit -m "auto update at ${{ env.UPDATE_TIME }}" --allow-empty
          git -C release push
