name: Update News Information

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * Sun'
    - cron: '*/5 * * * Mon-Fri'
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:

      - name: set variables
        run: |
          echo "UPDATE_TIME=$(TZ='Asia/Jakarta' date +%Y-%m-%d\ %H:%M)" >> $GITHUB_ENV

      - name: set up python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          
      - name: prepare release
        uses: actions/checkout@v3
        with: 
          path: release
          ref: main
          
      - name: prepare generater
        uses: actions/checkout@v3
        with: 
          repository: Qst236/getnews
          ssh-key: ${{ secrets.GETNEWS }}
          path: getnews
          ref: main

      - name: ls dir
        run: ls
          
      - name: install dependencies & get new news file
        run: |
          pip install -r getnews/requirements.txt
          python3 getnews/main.py --file release/news.json

      - name: ls dir
        run: ls

      - name: ls getnews
        run: ls getnews

      - name: ls release
        run: ls release
      
      - name: push release
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add news.json
          git commit -m "auto update at ${{ env.UPDATE_TIME }}" --allow-empty
          git push
